### ISSUE TITLE
the models path

### ISSUE THREAD

**Issue by oceanzwq** [Moreno98/Vision-Language-Bias-Control#3]
Hello, 

Is it correct to download and unzip the models file and place it in the path "/root/Vision-Language-Bias-Control-main/models"? 

Thanks！

**Comment by Moreno98** [comment]
Hi, yes, the models have to be placed under the `models` folder of the root. 
The final path should look like this: `Vision-Language-Bias-Control/models` and place the `ContraCLIP` and `pretrained` downloaded folders under `models/`.

**Comment by oceanzwq** [comment]
Thank you! I don’t seem to find the celebA-HQ data set in this project. Do I need to download it myself and upload it to the project?

**Comment by Moreno98** [comment]
Yes, as it is publicly available, we did not provide CelebA-HQ in the repo.

**Comment by oceanzwq** [comment]
Hello, could you please tell me where to download fair_face_pseudo_labels.txt from, thank you!

**Comment by Moreno98** [comment]
Hi, we did not provide this file as the pseudo labels may be inferred using FairFace. 
Nevertheless, we make this file available now [here](https://drive.google.com/file/d/1uyy0H3ShbAvTr_7bdADe82BGMOtzgDCw/view?usp=sharing).
Thank you!

**Comment by oceanzwq** [comment]
Thank you very much for your help, but I see that the Protected attribute is "Young" or "Skin_Color". Can I modify the gender attribute, for example? If possible, how should it be modified?

Thanks！
